# Generated by Django 3.0.5 on 2020-04-26 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0002_auto_20200426_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_name',
        ),
    ]
